#apiVersion: v1
#kind: Namespace
#metadata:
#  name: lazy-koala
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: gazer-config
#  namespace: lazy-koala
#data:
#  config.yaml: |
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gazer
  namespace: lazy-koala
  labels:
    app: gazer
spec:
  selector:
    matchLabels:
      name: gazer
  template:
    metadata:
      labels:
        name: gazer
      annotations:
        lazy-koala/scrape: "true"
    spec:
      containers:
        - name: gazer
          image: ghcr.io/mrsupiri/lazy-koala/gazer:latest
          ports:
            - containerPort: 8000
              name: metrics
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              ephemeral-storage: "2Gi"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONWARNINGS
              value: "ignore:Unverified HTTPS request"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
            - name: debug
              mountPath: /sys/kernel/debug
              readOnly: false
            - name: config
              mountPath: "/gazer/config"
              readOnly: true
      hostNetwork: true
      hostPID: true
      serviceAccountName: gazer
      initContainers:
        - name: init-headers
          image: ghcr.io/mrsupiri/lazy-koala/gazer:init
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
      volumes:
        - name: lsb-release
          hostPath:
            path: /etc/lsb-release
        - name: os-release
          hostPath:
            path: /etc/os-release
        - name: modules-dir
          hostPath:
            path: /var/cache/linux-headers/modules_dir
        - name: linux-headers-generated
          hostPath:
            path: /var/cache/linux-headers/generated
        - name: boot-host
          hostPath:
            path: /
        - name: modules-host
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
        - name: config
          configMap:
            name: gazer-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: lazy-koala
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: gazer
      containers:
        - name: prometheus
          image: prom/prometheus:v2.33.1
          ports:
            - containerPort: 9090
              name: default
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      nodeName: minikube
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gazer
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - podmetrics
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gazer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gazer
subjects:
  - kind: ServiceAccount
    name: gazer
    namespace: lazy-koala
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gazer
  namespace: lazy-koala
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lazy-koala
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'lazy-koala'
        scrape_interval: 1s
        metrics_path: /
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotationpresent_lazy_koala_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          regex: metrics
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: gazer
